DOPS-291: traefik install error
make deploy-prerequisites
.
.
.    
    helm repo add --force-update traefik https://traefik.github.io/charts
    "traefik" has been added to your repositories
    helm repo update
    Hang tight while we grab the latest from your chart repositories...
    ...Successfully got an update from the "traefik" chart repository
    ...Successfully got an update from the "jetstack" chart repository
    Update Complete. ⎈Happy Helming!⎈
    helm upgrade --install traefik traefik/traefik \
            --create-namespace --namespace traefik \
            --values hack/traefik-helm-values.yaml
    Release "traefik" does not exist. Installing it now.
    coalesce.go:286: warning: cannot overwrite table with non table for traefik.ports.traefik.expose (map[default:false])
    coalesce.go:286: warning: cannot overwrite table with non table for traefik.ports.websecure.expose (map[default:true])
    Error: template: traefik/templates/service.yaml:27:12: executing "traefik/templates/service.yaml" at <index (default dict $config.expose) $name>: error calling index: can't index item of type bool
    make: *** [Makefile:233: deploy-traefik] Error 1